title: Hamish555
description: Documentation for Hamish555's Code
theme: just-the-docs

url: https://github.com/thehamish555/thehamish555.github.io

# aux_links:
#   Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME